# Generated by Django 4.0.4 on 2022-04-23 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_info',
            fields=[
                ('package_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('destination_x', models.IntegerField()),
                ('destination_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Truck_info',
            fields=[
                ('truck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('truck_status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('description', models.CharField(max_length=64)),
                ('count', models.IntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_product', to='ups_front.package_info')),
            ],
        ),
        migrations.AddField(
            model_name='package_info',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_package', to='ups_front.truck_info'),
        ),
        migrations.AddField(
            model_name='package_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_package', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Feedback_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
