# Generated by Django 4.0.4 on 2022-04-24 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups_front', '0003_alter_package_info_user'),
    ]

    operations = [
    ]
