# Generated by Django 4.0.4 on 2022-04-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups_front', '0004_auto_20220424_0323'),
    ]

    operations = [
    ]
